Use all cores for SELinux restorecon
openSUSE/microos-tools pull request #31
Opened 2024-04-19 14:40 UTC by sysrich

restorecon has the -T option to set how many cores are used for setting labels

The default is 1

Setting -T 0 uses all cores, which makes perfect sense considering we're blocking the boot while restoring here - those cores aren't going to be doing anything else

On an old Dell XPS13 this results in the following kind of speedup

2476k files with default single threaded operation - 2m23.455s

same fileset with -T 0 (4 core CPU) - 1m3.572s

That's quite a speedbost IMO

2024-04-19 14:48 UTC, Conan-Kudo commented
Huh, I wonder why upstream doesn't default to `-T 0`...

2024-04-19 14:49 UTC, sysrich commented
@Conan-Kudo because running restorecon interactively on your system suddenly eating ALL THE CORES probably isn't a good idea

But here where we're running it on boot..absolutely, we should use -T 0 in my opinion

2024-04-19 14:53 UTC, Conan-Kudo commented
Yeah, that absolutely makes sense.

2024-04-19 14:53 UTC, Conan-Kudo approved these changes

2024-04-19 14:55 UTC, Conan-Kudo commented
Though the upstream autorelabel service could also use `-T 0`, does it?

2024-04-19 15:05 UTC, sysrich commented
as far as I've been able to glean, upstream autorelabel uses fixfiles which doesn't call restorecon with -T 0

but they also seem to do tons of fancy magic about not relabelling everything and doing it less often than we do..so , horses for courses I guess

2024-04-19 15:09 UTC, Conan-Kudo commented
Well, then. 🤷🏾‍♂️

2024-04-23 14:37 UTC, sysrich commented
Adjusted to do the same to setfiles in the dracut module also

2024-04-23 14:57 UTC, Conan-Kudo approved these changes

2024-04-29 09:35 UTC, Vogtinator approved these changes
The autorelabel units run in parallel with each other but only `/var` and `/home` likely have any significant content, I think a 2x thread use is fine.

2024-04-29 09:36 UTC, Vogtinator commented on selinux/98selinux-microos/selinux-microos-relabel.sh
> +        LANG=C chroot "$ROOT_SELINUX" find /etc -depth -exec /sbin/setfiles $FORCE -T 0 "/etc/selinux/${SELINUXTYPE}/contexts/files/file_contexts" \{\} +
Actually, `-T0` might break the workaround here. The label for the parent *must* be applied after the child. If threading changes the order, it'll break.

2024-04-29 09:36 UTC, Vogtinator requested changes
Actually, for `/etc` we can't use `-T0` ATM...

2024-09-23 11:40 UTC, ca-hu commented
okay sorry i had a drive-by idea while working on another bug... so please let me know if that will obviously not work and this is the wrong place to discuss this

instead of using multiple cores, there is `fixfiles -C`. if we provide the previous file context in e.g. /etc/selinux/targeted/contexts/files/file_contexts.pre fixfiles should take the diff and that might make things quicker?

aka if we dont remove file_contexts.pre in line 233 in https://build.opensuse.org/projects/security:SELinux/packages/selinux-policy/files/selinux-policy.spec?expand=1 for transactional systems, could you take the input and change the line to fixfiles -C?

2024-09-23 11:54 UTC, Vogtinator commented
`fixfiles -C` looks interesting.

It's not trivial to get the previous file contexts. As long as the policy is stored in `/var` it's even impossible if an update was skipped. It's also technically possible to have multiple snapshots which haven't been relabelled yet. Each would have their own specific "previous contexts" file.

There's the long-standing issue that we're already not relabelling enough: When booting older snaphots like after a rollback, it might be necessary to relabel `/var`, `/opt` and others to match the expected contexts. Having a diff might help here, but that also needs to be tracked somehow.

IMO trying `-T0` for all but `/etc` for now should be enough. If it turns out it's still too slow (hard I/O bottleneck?) we can try something with the diff functionality.

2024-09-25 12:26 UTC, Vogtinator commented
> IMO trying -T0 for all but /etc for now should be enough. If it turns out it's still too slow (hard I/O bottleneck?) we can try something with the diff functionality.

I pushed that change to this PR and gave it a try - works as expected! In a VM with `-smp 4` I get a ~4x speedup for the relabelling.

2024-09-25 12:27 UTC, Vogtinator approved these changes

2024-09-25 12:27 UTC, merged